# -*- coding: utf-8 -*-
"""Handwritten Digit Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wQXRl0nNSZCezkD8JEUN6kNeX-ebZdy
"""

from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images = train_images.astype('float32') / 255.0
test_images = test_images.astype('float32') / 255.0

from tensorflow.keras import layers,models

model=models.Sequential([
    layers.Flatten(input_shape=(28,28)),
    layers.Dense(128,activation='relu'),
    layers.Dense(10,activation='softmax')
])

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(train_images,train_labels,epochs=5,batch_size=32,validation_data=(test_images,test_labels))

test_loss,test_acc=model.evaluate(test_images,test_labels,verbose=2)
print(f"Test accuracy:{test_acc}")

import numpy as np
predictions=model.predict(test_images)
print(f"First prediction:{np.argmax(predictions[0])}, Actual Label:{test_labels[0]}")

